### ISSUE TITLE
Add a mark to indicate whether the resource is free, paid, etc.

### ISSUE THREAD

**Issue by blzaugg** [cfj/awesome-code-schools#6]
Add a mark to indicate whether the resource is free, paid, etc.

**Example:**
- [Code Avengers](http://www.codeavengers.com)\* - HTML, CSS, JavaScript
- [Codecademy](http://www.codecademy.com) - HTML, CSS, JavaScript, jQuery, Python, Ruby, PHP

*_Note: Paid membership or purchase required for some or all content._

**Comment by cfj** [comment]
This is a good idea. Thanks.

**Comment by cfj** [comment]
Added in 5b50b8f.
